import type { HubCard } from "./types";

export const hubSearchOptions = [
  "Search by ZIP code",
  "Search by city",
  "Search by county",
  "Location requires your permission",
] as const;

export const hubCards: HubCard[] = [
  {
    id: "eastview-library",
    name: "Eastview Public Library",
    hubType: "Community location",
    address: "100 Main Street",
    city: "Eastview",
    county: "Eastview County",
    zipCode: "75001",
    distanceLabel: "0.4 mi",
    hours: "Mon-Sat, 9:00 AM-5:00 PM",
    accessSupport: ["Digital help", "Health Access Day information", "Provider platform readiness"],
    accessibilityNotes: "Accessible entrance and public computers available.",
    phoneOrWebsite: "Website available when live directory is enabled",
    directionsLabel: "Directions are available soon.",
    verificationStatus: "Resource listing",
    lastUpdated: "2026-06-01",
    privacyNote: "No private health information is needed to browse this listing.",
    partnerStatus: "Listed access point. Formal partnership is not implied.",
    latitude: 32.7767,
    longitude: -96.797,
  },
  {
    id: "hope-community-center",
    name: "Hope Community Center",
    hubType: "Community access point",
    address: "200 Oak Avenue",
    city: "Eastview",
    county: "Eastview County",
    zipCode: "75001",
    distanceLabel: "0.6 mi",
    hours: "Tue-Thu, 10:00 AM-4:00 PM",
    accessSupport: ["Community support", "Event information", "Digital readiness help"],
    accessibilityNotes: "Ground-level entrance and seating available.",
    phoneOrWebsite: "Contact details can be added after verification.",
    directionsLabel: "Directions are available soon.",
    verificationStatus: "Resource listing",
    lastUpdated: "2026-06-01",
    privacyNote: "Browsing this listing does not create a profile.",
    partnerStatus: "Community location. Formal partnership is not implied.",
    latitude: 32.779,
    longitude: -96.802,
  },
  {
    id: "faith-in-action-center",
    name: "Faith in Action Center",
    hubType: "Resource listing",
    address: "300 Pine Street",
    city: "Eastview",
    county: "Eastview County",
    zipCode: "75001",
    distanceLabel: "1.2 mi",
    hours: "Wed-Fri, 11:00 AM-3:00 PM",
    accessSupport: ["Provider pathway preparation", "Digital help", "Community resource awareness"],
    accessibilityNotes: "Call ahead may be useful for accessibility details.",
    phoneOrWebsite: "Contact details can be added after verification.",
    directionsLabel: "Directions are available soon.",
    verificationStatus: "Needs human review before public use",
    lastUpdated: "2026-06-01",
    privacyNote: "No diagnosis, treatment, or insurance information is requested.",
    partnerStatus: "Resource listing. Formal partnership is not implied.",
    latitude: 32.771,
    longitude: -96.79,
  },
];
