import type { DataClassification } from "./types";

export const privacyBoundaryText = [
  "No PHI. Consent-based. Non-clinical.",
  "We do not diagnose.",
  "We do not treat.",
  "We do not prescribe.",
  "We do not replace licensed care.",
  "You control what you choose to share.",
] as const;

export const privacyExplanations = {
  microphone:
    "Microphone access is optional. You can type instead. Raw audio should not be stored by default.",
  location:
    "Location is optional. ZIP code, city, and county search are available. No background tracking or location history is used.",
  typing:
    "Typing lets you use Voice Access-style guidance without speaking.",
  zip:
    "ZIP code search can help find nearby hubs or events without current-location permission.",
  notRequired:
    "Name, phone, email, address, symptoms, diagnosis, insurance, appointment details, and provider relationship are not required for basic app use.",
} as const;

export const dataClassification: DataClassification[] = [
  {
    category: "No data collected",
    purpose: "Basic browsing and reading guidance",
    required: "No",
    stored: "No",
    retention: "None",
    consent: "Not required",
    deletion: "Nothing to delete",
    risk: "Low",
    residentExplanation: "You can browse without creating an account or sharing private information.",
  },
  {
    category: "Session-only app state",
    purpose: "Remember the screen, selected need, or local search while the app is open",
    required: "No",
    stored: "No persistent storage in V0",
    retention: "Current session only",
    consent: "Implied by use of the app",
    deletion: "Clears when the session ends",
    risk: "Low",
    residentExplanation: "The app may remember your choice while you are using it.",
  },
  {
    category: "Optional contact data",
    purpose: "Future follow-up or reminders only if separately approved",
    required: "No",
    stored: "Not in V0",
    retention: "Future policy required",
    consent: "Explicit consent required before any future use",
    deletion: "Future deletion path required before launch",
    risk: "Medium",
    residentExplanation: "Contact sharing is not active in this foundation.",
  },
  {
    category: "Location data",
    purpose: "Show nearby hubs or events",
    required: "No",
    stored: "No in V0",
    retention: "Session only if enabled later",
    consent: "Explicit location permission required",
    deletion: "No location history is kept in V0",
    risk: "Medium",
    residentExplanation: "Location is optional and only used to find nearby access options.",
  },
  {
    category: "ZIP code search",
    purpose: "Find nearby hubs or events without current location",
    required: "No",
    stored: "No persistent storage in V0",
    retention: "Current session only",
    consent: "Resident enters it voluntarily",
    deletion: "Clears when the session ends",
    risk: "Low",
    residentExplanation: "You can use a ZIP code instead of sharing location.",
  },
  {
    category: "Voice input",
    purpose: "Future microphone-based Voice Access",
    required: "No",
    stored: "No raw audio storage by default",
    retention: "Temporary processing only in a future approved model",
    consent: "Explicit microphone consent required",
    deletion: "Future transcript policy required before live launch",
    risk: "Medium",
    residentExplanation: "Voice is optional. You can type instead.",
  },
  {
    category: "AI transcript",
    purpose: "Future AI guidance response generation",
    required: "No",
    stored: "Not in V0",
    retention: "Future consent and retention model required",
    consent: "Explicit AI-assisted guidance consent required",
    deletion: "Future deletion path required before launch",
    risk: "Medium",
    residentExplanation: "AI guidance is not medical advice and is not live in V0.",
  },
  {
    category: "Event interest",
    purpose: "Future event readiness and reminders",
    required: "No",
    stored: "Not in V0",
    retention: "Future policy required",
    consent: "Explicit consent required before reminders",
    deletion: "Future deletion path required before launch",
    risk: "Low",
    residentExplanation: "Browsing event cards does not sign you up.",
  },
  {
    category: "Hub search",
    purpose: "Find access points",
    required: "No",
    stored: "No persistent storage in V0",
    retention: "Current session only",
    consent: "Resident enters search voluntarily",
    deletion: "Clears when the session ends",
    risk: "Low",
    residentExplanation: "You can browse example hubs without sharing private information.",
  },
  {
    category: "Future account data",
    purpose: "Not active; would support saved preferences only after review",
    required: "No",
    stored: "Not in V0",
    retention: "Future policy required",
    consent: "Explicit account consent required",
    deletion: "Future deletion path required before launch",
    risk: "Medium",
    residentExplanation: "Accounts are not part of this foundation.",
  },
];
