import type { DataClassification } from "./types";

export const privacyBoundaryText = [
  "No PHI. Consent-based. Non-clinical.",
  "We do not give medical advice.",
  "We do not replace licensed care.",
  "You control what you choose to share.",
] as const;

export const privacyExplanations = {
  microphone:
    "Microphone access requires your permission before it can be used. You can use guided text instead. Raw audio and transcripts are not stored.",
  location:
    "Location is optional. ZIP code, city, and county search are available. No background tracking or location history is used.",
  typing:
    "Typing lets you use Voice Access-style guidance without live speech.",
  zip:
    "ZIP code search can help find nearby hubs or events without location sharing.",
  notRequired:
    "Name, phone, email, address, symptoms, insurance, visit details, and provider relationship are not required for basic app use.",
} as const;

export const dataClassification: DataClassification[] = [
  {
    category: "No data collected",
    purpose: "Basic browsing and reading guidance",
    required: "No",
    stored: "No",
    retention: "None",
    consent: "Not required",
    deletion: "Nothing to delete",
    risk: "Low",
    residentExplanation: "You can browse without creating an account or sharing private information.",
  },
  {
    category: "Session-only app state",
    purpose: "Remember the screen, selected need, or local search while the app is open",
    required: "No",
    stored: "No persistent storage in controlled launch v1",
    retention: "Current session only",
    consent: "Implied by use of the app",
    deletion: "Clears when the session ends",
    risk: "Low",
    residentExplanation: "The app may remember your choice while you are using it.",
  },
  {
    category: "Optional contact data",
    purpose: "Future follow-up or reminders only if separately approved",
    required: "No",
    stored: "Not stored in controlled launch v1",
    retention: "Future policy required",
    consent: "Explicit consent required before any future use",
    deletion: "Future deletion path required before launch",
    risk: "Medium",
    residentExplanation: "Contact sharing requires your permission before SozoRock can respond.",
  },
  {
    category: "Location data",
    purpose: "Show nearby hubs or events",
    required: "No",
    stored: "No in controlled launch v1",
    retention: "Session only if enabled later",
    consent: "Future explicit location permission required",
    deletion: "No location history is kept in controlled launch v1",
    risk: "Medium",
    residentExplanation: "Location needs your permission before it can be used; ZIP code, city, and county search remain available.",
  },
  {
    category: "ZIP code search",
    purpose: "Find nearby hubs or events without location sharing",
    required: "No",
    stored: "No persistent storage in controlled launch v1",
    retention: "Current session only",
    consent: "Resident enters it voluntarily",
    deletion: "Clears when the session ends",
    risk: "Low",
    residentExplanation: "You can use a ZIP code instead of sharing location.",
  },
  {
    category: "Voice input",
    purpose: "Permission-based Voice Access",
    required: "No",
    stored: "No raw audio or transcript storage in controlled launch v1",
    retention: "Temporary processing only in an approved model",
    consent: "Explicit microphone consent required",
    deletion: "Transcript policy required before live audio launch",
    risk: "Medium",
    residentExplanation: "Voice Access is limited access. You can use guided text instead.",
  },
  {
    category: "AI transcript",
    purpose: "Approved AI guidance response generation",
    required: "No",
    stored: "Not stored in controlled launch v1",
    retention: "Consent and retention model required before provider enablement",
    consent: "Explicit AI guidance consent required",
    deletion: "Deletion path required before support storage",
    risk: "Medium",
    residentExplanation: "AI guidance is not medical advice and remains limited access until safety review passes.",
  },
  {
    category: "Event interest",
    purpose: "Event readiness and reminders when approved",
    required: "No",
    stored: "Not stored in controlled launch v1",
    retention: "Policy required before reminders",
    consent: "Explicit consent required before reminders",
    deletion: "Future deletion path required before launch",
    risk: "Low",
    residentExplanation: "Browsing event cards does not sign you up.",
  },
  {
    category: "Hub search",
    purpose: "Find access points",
    required: "No",
    stored: "No persistent storage in controlled launch v1",
    retention: "Current session only",
    consent: "Resident enters search voluntarily",
    deletion: "Clears when the session ends",
    risk: "Low",
    residentExplanation: "You can browse reviewed hubs without sharing private information.",
  },
  {
    category: "Saved preferences",
    purpose: "Available soon; would support saved preferences only after review",
    required: "No",
    stored: "Not stored in controlled launch v1",
    retention: "Policy required before saved preferences",
    consent: "Explicit account consent required",
    deletion: "Deletion path required before saved preferences",
    risk: "Medium",
    residentExplanation: "Saved preferences are available soon.",
  },
];
